# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
# TODO(iurygregory): update this after have information
title: "OpenStack Days Natal"
email: ""
description: ""
baseurl: ""
url: "http://natal.openstackdays.com.br"

# Organizer Info
organizerName: "OpenStack Days Natal Group"
organizerAlternateName: "OpenStack Days Natal"
organizerDescription: "Group of peoplpe excited about Cloud Computing and OpenStack"
organizerEmail: ""
organizerLogo: ""
organizerLink: ""

# Head
metaKeywords: ""
twitterAccount: ""
socialImageSrcTwitter: "/img/sharing-twitter.png"
socialImageSrcFacebook: "/img/sharing-facebook.png"

# Documents
c4pUrl: ""
c4sponsorsUrl: "/assets/SponsorshipProspectus_Enterprise.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
bottomNavigationLinks:
 - {link: "", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "", text: "Become a speaker"}

# Hero Block
heroImage: "hero01.jpeg"
heroTitle: "OpenStack Days Natal <typeout> 2016"
eventDate: "November 19th, 2016"
heroButtons:
# - {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {link: "https://www.eventbrite.com/e/openstack-day-natal-tickets-27410957913", text: "Buy tickets"}

# About Block
aboutTitle: "About OpenStack Days Natal"
aboutBlock:
 - {title: "Event", image: "BADGE_1_NATAL-01.png", text: "First OpenStack Days event to be held in the northeast of Brazil in Natal!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: ""
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: ""
eventLocationLink: ""
eventStreetAddress: "Rua Francisco Gurgel, 33, Ponta Negra, Natal, RN, Brasil"
eventAddressLocality: "Natal"
eventAddressLocalityRegion: ""
eventPostalCode: "59000"
eventAddressCountry: "Brazil"
eventStartTime: "2016-11-19T09:00"
eventDoorTime: "08:00"
eventEndTime: "2016-11-19T18:15"
eventPlaceCoordinates: "-5.872569, -35.1783299"
mapCenterCoordinates: "-5.872569, -35.1783299"
mapMobileCenterCoordinates: "-5.872569, -35.1783299"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Praiamar Hotel & Convention"
venueFeatures: ["Best location in Ponta Negra Beach", "A huge and confortable auditorium", "Great leisure space"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
advisoryTitle: "Advisory Group"
staffTitle: "Staff Group"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes.//\nAccommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "25"
  priceCurrency: "BRL"
  ticketsNumber: "150"
  buyButtonLink: "https://www.eventbrite.com/e/openstack-day-natal-tickets-27410957913"
  buyButtonText: "Buy Now"
  ticketContentList: [] #"Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2016-11-19T09:00"
  validThrough: "2016-11-19T18:15"

# Footer
socialLinks:
 - {link: "", icon: "twitter"}
 - {link: "", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "", text: ""}
   - {link: "", text: ""}
 -
  title: "Contacts"
  links:
   - {link: "", text: ""}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: ""

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Natal-RN"
directionDetailsCards:
 - {title: "From the Airport", information: '34km by car. Less than 50 minutes.'}
 - {title: "Public Transit", information: '14 minutes from Arena das Dunas Stadium by car. 13 minutes from Via Mar Shopping
 walk. 22 minutes by car from the biggest cashew tree in the world'}
 - {title: "Hotels", information: 'The event hotel will be Praiamar Natal Hotel&Convention. More information you can find <a href="http://www.praiamarnatal.com.br/">here</a>.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "http://www.praiamarnatal.com.br/", text: "PraiamarNatal"}
   -
    title: "Registration"
    links:
     - {link: "http://www.praiamarnatal.com.br/", text: "PraiamarNatal"}
   -
    title: "Attendance Details"
    links:
     - {link: "http://www.praiamarnatal.com.br/", text: "PraiamarNatal"}
