# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
# TODO(iurygregory): update this after have information
title: "OpenStack Days Natal"
email: "openstackdaysnatal@gmail.com."
description: ""
baseurl: ""
url: "http://natal.openstackdays.com.br"
#permalink: "/blog/:title"
#url: "http://natal.openstackdays.com.br"
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "gdg-x.github.io"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "OpenStack Days Natal Group"
organizerAlternateName: "OpenStack Days Natal"
organizerDescription: "Group of peoplpe excited about Cloud Computing and OpenStack"
organizerEmail: "openstackdaysnatal@gmail.com"
organizerLogo: ""
organizerLink: ""

# Head
metaKeywords: ""
twitterAccount: ""
socialImageSrcTwitter: "/img/sharing-twitter.png"
socialImageSrcFacebook: "/img/sharing-facebook.png"

# Documents
c4pUrl: "https://goo.gl/forms/NxnHIPfpFHidOEb92"
c4sponsorsUrl: "/assets/SponsorshipProspectus_Enterprise.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Início"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/programacao/", text: "Programação"}
 - {permalink: "/palestrantes/", text: "Palestrantes"}
 - {permalink: "/equipe/", text: "Equipe"}
 - {permalink: "/local/", text: "Local"}
bottomNavigationLinks:
 - {link: "https://goo.gl/forms/NxnHIPfpFHidOEb92", text: "Chamada de Apresentações"}
rightNavigationButtons:
 - {link: "https://goo.gl/forms/NxnHIPfpFHidOEb92", text: "Chamada de Apresentações"}

# Hero Block
heroImage: "hero01.jpeg"
heroTitle: "OpenStack Days Natal <typeout> 2016"
eventDate: "19 de Novembro 2016"
typeoutTextValues: '"", "Season", "Ukraine", "Germany", "USA"'
typeoutFallback: "Season"
heroButtons:
 - {link: "https://www.eventbrite.com/e/openstack-day-natal-tickets-27410957913", text: "Inscrições"}

# About Block
aboutTitle: "Sobre OpenStack Days Natal 2016"
aboutBlock:
 - {title: "", image: "BADGE_1_NATAL-01.png", text: "O primeiro evento
   OpenStack Days a ser realizado na região Nordeste do Brasil na cidade de
Natal no Rio Grande do Norte! Não perca esta grande oportunidade para
conhecer líderes da indústria, usuários da comunidade OpenStack, compartilhar
conhecimentos e discutir sobre como OpenStack pode ser útil!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Últimas notícias"

# Rockstar Speakers Block
rockstarSpeakersImage: ""
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Palestrantes"
rockstarSpeakersButtonText: "Veja todos os palestrantes"

# Location Block
locationBlockTitle: "Localização"
eventLocationName: ""
eventLocationLink: ""
eventStreetAddress: "Rua Francisco Gurgel, 33, Ponta Negra, Natal, RN, Brasil"
eventAddressLocality: "Natal"
eventAddressLocalityRegion: ""
eventPostalCode: "59000"
eventAddressCountry: "Brazil"
eventStartTime: "2016-11-19T09:00"
eventDoorTime: "08:00"
eventEndTime: "2016-11-19T18:15"
eventPlaceCoordinates: "-5.872569, -35.1783299"
mapCenterCoordinates: "-5.872569, -35.1783299"
mapMobileCenterCoordinates: "-5.872569, -35.1783299"

# Venue Block
venueBlockTitle: "Local"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Praiamar Hotel & Convention"
venueFeatures: ["Melhor localização na Praia de Ponta Negra", "Auditório
confortável", "Possui ótimo espaço para lazer"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Patrocinadores"
#partnersC4sponsorsButton: "Seja um patrocinador"

# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned"

# Tickets Block
ticketsTitle: "Tabela de Preço"
ticketsInfo: "Os ingressos garantem acesso a todas as palestras e lanches.//\nA hospedagem não está inclusa no preço do ingresso."
ticketsOffers:
 -
  name: "Ingresso Promocional"
  price: "R$ 25"
  priceCurrency: ""
  ticketsNumber: "100"
  featured: true
  buyButtonLink: "https://www.eventbrite.com/e/openstack-day-natal-tickets-27410957913"
  buyButtonText: "Compre agora"
  ticketContentList: ["Garanta já o seu ingresso", "Desconto de 50% até 06 de Novembro"] #"Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2016-09-09T09:00"
  validThrough: "2016-11-06T23:59"
  disabled: false
 -
  name: "Ingresso Regular"
  price: "R$ 50"
  ticketsNumber: "100"
#  buyButtonLink: "https://www.eventbrite.com/e/openstack-day-natal-tickets-27410957913"
  buyButtonText: ""
  ticketContentList: ["Vendas a partir de 07 de Novembro ou até acabarem as unidades"]
  validFrom: "2016-09-09T00:00"
  validThrough: "2016-11-19T08:00"

# Footer
socialLinks:
   - {link: "https://twitter.com/openstacknatal", icon: "twitter"}
   - {link: "http://fb.me/OpenStackDaysNatal", icon: "facebook"}
footerBlocks:
 -
  title: "Contato"
  links:
   - {link: "mailto:openstackdaysnatal@gmail.com", text: "openstackdaysnatal@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de Conduta"}

# Blog
blogTitle: "Últimas notícias"
blogCommentsEnabled: true
discusShortName: "OpenStackDaysNatal"

# Speakers List Block
showSessions: true

# Team Block
# Colocar texto aqui "Quem somos?" "..."
teamBlockTitle: ""
aboutUs: ""

# Logistics Find Way Block
findWayTitle: "Como chegar ao Evento"
findWayDistance: "Distância"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Natal-RN"
directionDetailsCards:
 - {title: "Aeroporto", information: '34km de distância, menos de 50 minutos de carro.'}
 - {title: "Trânsito", information: '14 minutos de carro do Estádio Arena das Dunas. 13 minutos a pé do Via Mar Shopping. 22 minutos de carro do maior cajueiro do mundo.'}
 - {title: "Hotel", information: 'O Hotel do evento será o Praiamar Natal Hotel&Convention. Para mais informações acesse o site do <a href="http://www.praiamarnatal.com.br/">Hotel</a>.'}
directionDetailsWideCards:
 -
  title: "Perguntas?"
  subCards:
   -
    title: "Hotel"
    links:
     - {link: "http://www.praiamarnatal.com.br/", text: "PraiamarNatal"}
   -
    title: "Reservas"
    links:
     - {link: "http://www.praiamarnatal.com.br/", text: "PraiamarNatal"}
   -
    title: "Detalhes"
    links:
     - {link: "http://www.praiamarnatal.com.br/", text: "PraiamarNatal"}
